'use strict';
/**
 * Shared branded header for every PDFKit document this app generates
 * (receipts, invoices, statements, lease agreements).
 *
 * Previously each of the 4 PDF generators (services/pdf.js,
 * invoicePdf.js, statementPdf.js, leasePdf.js) drew its own ad-hoc
 * header: a blue (#0369a1) band with plain bold text, no logo mark at
 * all. That blue has no relationship to the app's actual brand — the
 * real brand color (used everywhere in the frontend: the sidebar
 * square, the "Nyumba" half of the wordmark) is amber (--brand:
 * #D97706 in frontend/src/index.css), and the actual logo is a house
 * glyph in a rounded amber square (see the "Brand" block in
 * frontend/src/components/layout/Sidebar.jsx) — not just text.
 *
 * This draws that same mark (the exact SVG path from the sidebar,
 * reused via PDFKit's SVG-path support so it's pixel-faithful, not a
 * redrawn approximation) plus the two-tone "Smart"/"Nyumba" wordmark,
 * on the same dark band color as the sidebar (--sidebar-bg: #0C1117),
 * so every document a tenant or owner receives actually looks like it
 * came from this product.
 */

const BRAND       = '#D97706'; // frontend/src/index.css --brand (light theme)
const SIDEBAR_BG  = '#0C1117'; // frontend/src/index.css --sidebar-bg
// Exact glyph from frontend/src/components/layout/Sidebar.jsx's brand mark
// (20x20 viewBox), respaced for PDFKit's SVG-path tokenizer: PDFKit's
// parser is a simple tokenizer, not a full SVG path grammar, and chokes
// on the compact arc-flag notation the original (heroicons-style) path
// uses — flags glued directly to a following signed number with no
// separator (e.g. "00-1.414"). Values are unchanged, just spaced out so
// each token parses correctly; rendering was checked visually.
const HOUSE_PATH  = 'M10.707 2.293 a1 1 0 0 0 -1.414 0 l-7 7 a1 1 0 0 0 1.414 1.414 L4 10.414 V17 a1 1 0 0 0 1 1 h4 a1 1 0 0 0 1 -1 v-3 h2 v3 a1 1 0 0 0 1 1 h4 a1 1 0 0 0 1 -1 v-6.586 l0.293 0.293 a1 1 0 0 0 1.414 -1.414 l-7 -7 z';

/** Draws the amber rounded-square house-glyph logo at (x, y), `size` px square. */
function drawLogoMark(doc, x, y, size = 32) {
  doc.roundedRect(x, y, size, size, size * 0.3).fill(BRAND);
  const scale  = (size * 0.55) / 20; // glyph is on a 20x20 viewBox
  const offset = size * 0.225;
  doc.save();
  doc.translate(x + offset, y + offset);
  doc.scale(scale);
  doc.path(HOUSE_PATH).fill('white');
  doc.restore();
}

/**
 * Draws the full branded header band across the top of the current
 * page: logo + "SmartNyumba" wordmark on the left, document-specific
 * lines (title, reference, date, etc.) right-aligned. Returns the y
 * coordinate just below the band, so callers know where to start
 * their own content.
 *
 * @param {PDFDocument} doc
 * @param {object} opts
 * @param {string}   [opts.subtitle]   e.g. a property name/location line under the wordmark
 * @param {string}   [opts.docTitle]   e.g. "TAX INVOICE", "PAYMENT RECEIPT"
 * @param {string[]} [opts.rightLines] extra right-aligned lines under docTitle (ref #, date, etc.)
 * @param {number}   [opts.height]     band height in points (default 100)
 * @param {number}   [opts.pageWidth]  page width in points (default 612 = A4 @ 72dpi)
 */
function drawBrandedHeader(doc, { subtitle, docTitle, rightLines = [], height = 100, pageWidth = 612 } = {}) {
  doc.rect(0, 0, pageWidth, height).fill(SIDEBAR_BG);

  const logoSize = 32;
  const logoY = 24;
  drawLogoMark(doc, 50, logoY, logoSize);

  doc.font('Helvetica-Bold').fontSize(17)
     .fill('white').text('Smart', 50 + logoSize + 12, logoY + 6, { continued: true })
     .fill(BRAND).text('Nyumba');

  if (subtitle) {
    doc.font('Helvetica').fontSize(10).fill('#94a3b8')
       .text(subtitle, 50 + logoSize + 12, logoY + 6 + 20);
  }

  if (docTitle) {
    doc.fill(BRAND).font('Helvetica-Bold').fontSize(13).text(docTitle, 380, logoY + 2, { width: 182, align: 'right' });
  }
  let ry = logoY + 20;
  doc.fill('white').font('Helvetica').fontSize(9);
  for (const line of rightLines) {
    doc.text(line, 380, ry, { width: 182, align: 'right' });
    ry += 14;
  }

  return height;
}

/** Small "generated by SmartNyumba Pro" footer line, consistent wording everywhere. */
function drawFooterLine(doc, x, y, width, extra = '') {
  doc.fill('#64748b').font('Helvetica').fontSize(9)
     .text(extra ? `${extra}` : '', x, y, { align: 'center', width })
     .text('Generated by SmartNyumba Pro', x, y + (extra ? 14 : 0), { align: 'center', width });
}

module.exports = { drawBrandedHeader, drawLogoMark, drawFooterLine, BRAND, SIDEBAR_BG };
